BEGIN;

INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (1, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (2, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (3, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (4, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (5, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (6, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (7, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (8, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (9, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (10, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (11, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (12, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (13, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (14, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (15, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (16, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (17, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (18, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (19, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (20, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (21, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (22, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (23, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (24, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (25, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (26, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (27, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (28, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (29, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (30, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (31, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (32, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (33, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (34, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (35, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (36, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (37, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (38, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (39, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (40, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (41, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (42, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (43, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (44, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (45, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (46, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (47, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (48, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (49, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (50, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (51, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (52, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (53, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (54, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (55, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (56, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (57, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (58, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (59, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (60, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (61, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (62, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (63, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (64, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (65, 1006, 2);
INSERT INTO yeshayahu (perek_id, teacher_id, part_id) VALUES (66, 1006, 2);

COMMIT;

BEGIN;

INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (1, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (2, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (3, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (4, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (5, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (6, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (7, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (8, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (9, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (10, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (11, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (12, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (13, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (14, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (15, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (16, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (17, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (18, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (19, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (20, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (21, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (22, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (23, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (24, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (25, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (26, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (27, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (28, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (29, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (30, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (31, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (32, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (33, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (34, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (35, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (36, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (37, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (38, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (39, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (40, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (41, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (42, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (43, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (44, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (45, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (46, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (47, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (48, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (49, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (50, 1007, 2);
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id ,is_many_parts, parts_breakdown) VALUES (51, 1007, 1, true, 'a,b');
INSERT INTO yirmiyahu (perek_id, teacher_id, part_id) VALUES (52, 1007, 2);

COMMIT;

BEGIN;

INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (1, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (2, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (3, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (4, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (5, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (6, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (7, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (8, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (9, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (10, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (11, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (12, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (13, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (14, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (15, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id, is_many_parts, parts_breakdown) VALUES (16, 1008, 1, true, 'a,b');
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (17, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (18, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (19, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id, is_many_parts, parts_breakdown) VALUES (20, 1008, 1, true, 'a,b');
INSERT INTO yehezkel (perek_id, teacher_id, part_id, is_many_parts, parts_breakdown) VALUES (21, 1008, 1, true, 'a,b');
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (22, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id, is_many_parts, parts_breakdown) VALUES (23, 1008, 1, true, 'a,b');
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (24, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (25, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (26, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (27, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (28, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (29, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (30, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (31, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (32, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (33, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (34, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (35, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id, is_many_parts, parts_breakdown) VALUES (36, 1008, 1, true, 'a,b');
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (37, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (38, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (39, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (40, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (41, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (42, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (43, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (44, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (45, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (46, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (47, 1008, 2);
INSERT INTO yehezkel (perek_id, teacher_id, part_id) VALUES (48, 1008, 2);

COMMIT;
