BEGIN;

INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (1, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (2, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (3, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (4, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (5, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (6, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (7, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (8, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (9, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (10, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (11, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (12, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (13, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (14, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (15, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (16, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (17, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (18, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (19, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (20, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (21, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (22, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (23, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (24, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (25, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (26, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (27, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (28, 1015, 4);
INSERT INTO divrehayamim1 (perek_id, teacher_id, part_id) VALUES (29, 1015, 4);

COMMIT;

BEGIN;

INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (1, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (2, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (3, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (4, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (5, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (6, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (7, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (8, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (9, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (10, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (11, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (12, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (13, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (14, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (15, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (16, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (17, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (18, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (19, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (20, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (21, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (22, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (23, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (24, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (25, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (26, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (27, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (28, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (29, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (30, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (31, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (32, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (33, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (34, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (35, 1015, 4);
INSERT INTO divrehayamim2 (perek_id, teacher_id, part_id) VALUES (36, 1015, 4);

COMMIT;

BEGIN;

INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (1, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (2, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (3, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (4, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (5, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (6, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (7, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (8, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (9, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (10, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (11, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (12, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (13, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (14, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (15, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (16, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (17, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (18, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (19, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (20, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (21, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (22, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (23, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (24, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (25, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (26, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (27, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (28, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (29, 1016, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (30, 1017, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (31, 1017, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (32, 1017, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (33, 1017, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (34, 1017, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (35, 1017, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (36, 1017, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (37, 1017, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (38, 1017, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (39, 1017, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (40, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (41, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (42, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (43, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (44, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (45, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (46, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (47, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (48, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (49, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (50, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (51, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (52, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (53, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (54, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (55, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (56, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (57, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (58, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (59, 1018, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (60, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (61, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (62, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (63, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (64, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (65, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (66, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (67, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (68, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (69, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (70, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (71, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (72, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (73, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (74, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (75, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (76, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (77, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (78, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (79, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (80, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (81, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (82, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (83, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (84, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (85, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (86, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (87, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (88, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (89, 1019, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (90, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (91, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (92, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (93, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (94, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (95, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (96, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (97, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (98, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (99, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (101, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (102, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (103, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (104, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (105, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (106, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (107, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (108, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (109, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (110, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (111, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (112, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (113, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (114, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (115, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (116, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (117, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (118, 1020, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id, is_many_parts, parts_breakdown) VALUES (119, 1021, 4, true, 'a,b,c,d');
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (120, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (121, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (122, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (123, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (124, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (125, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (126, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (127, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (128, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (129, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (130, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (131, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (132, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (133, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (134, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (135, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (136, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (137, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (138, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (139, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (140, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (141, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (142, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (143, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (144, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (145, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (146, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (147, 1021, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (148, 1001, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (149, 1022, 4);
INSERT INTO tehillim (perek_id, teacher_id, part_id) VALUES (150, 1021, 4);

COMMIT;

BEGIN;

INSERT INTO mishle (perek_id, teacher_id, part_id, is_many_parts, parts_breakdown) VALUES (1, 1023, 4, true, 'a,b');
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (2, 1023, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (3, 1023, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (4, 1023, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (5, 1023, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (6, 1023, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (7, 1023, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (8, 1023, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (9, 1023, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id, is_many_parts, parts_breakdown) VALUES (10, 1023, 4, true, 'a,b');
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (11, 1023, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (12, 1024, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (13, 1024, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id, is_many_parts, parts_breakdown) VALUES (14, 1024, 4, true, 'a,b');
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (15, 1024, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (16, 1024, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (17, 1024, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (18, 1024, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id, is_many_parts, parts_breakdown) VALUES (19, 1024, 4, true, 'a,b');
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (20, 1024, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (21, 1024, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id, is_many_parts, parts_breakdown) VALUES (22, 1024, 4, true, 'a,b');
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (23, 1024, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id, is_many_parts, parts_breakdown) VALUES (24, 1024, 4, true, 'a,b');
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (25, 1024, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (26, 1024, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (27, 1024, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (28, 1024, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id) VALUES (29, 1024, 4);
INSERT INTO mishle (perek_id, teacher_id, part_id, is_many_parts, parts_breakdown) VALUES (30, 1024, 4, true, 'a,b');
INSERT INTO mishle (perek_id, teacher_id, part_id, is_many_parts, parts_breakdown) VALUES (31, 1024, 4, true, 'a,b');

COMMIT;

BEGIN;

INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (1, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (2, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (3, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (4, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (5, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (6, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (7, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (8, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (9, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (10, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (11, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (12, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (13, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (14, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (15, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (16, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (17, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (18, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (19, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (20, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (21, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (22, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (23, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (24, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (25, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (26, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (27, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (28, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (29, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (30, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (31, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (32, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (33, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (34, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (35, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (36, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (37, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (38, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (39, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (40, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (41, 1015, 4);
INSERT INTO iyov (perek_id, teacher_id, part_id) VALUES (42, 1015, 4);

COMMIT;

BEGIN;

INSERT INTO shirhashirim (perek_id, teacher_id, part_id) VALUES (0, 1001, 4);
INSERT INTO shirhashirim (perek_id, teacher_id, part_id, is_many_parts, parts_breakdown) VALUES (1, 1001, 4, true, 'a,b');
INSERT INTO shirhashirim (perek_id, teacher_id, part_id) VALUES (2, 1001, 4);
INSERT INTO shirhashirim (perek_id, teacher_id, part_id) VALUES (3, 1001, 4);
INSERT INTO shirhashirim (perek_id, teacher_id, part_id) VALUES (4, 1001, 4);
INSERT INTO shirhashirim (perek_id, teacher_id, part_id) VALUES (5, 1001, 4);
INSERT INTO shirhashirim (perek_id, teacher_id, part_id) VALUES (6, 1001, 4);
INSERT INTO shirhashirim (perek_id, teacher_id, part_id) VALUES (7, 1001, 4);
INSERT INTO shirhashirim (perek_id, teacher_id, part_id) VALUES (8, 1001, 4);

COMMIT;

BEGIN;

INSERT INTO ruth (perek_id, teacher_id, part_id) VALUES (0, 1025, 4);
INSERT INTO ruth (perek_id, teacher_id, part_id) VALUES (1, 1025, 4);
INSERT INTO ruth (perek_id, teacher_id, part_id) VALUES (2, 1025, 4);
INSERT INTO ruth (perek_id, teacher_id, part_id) VALUES (3, 1025, 4);
INSERT INTO ruth (perek_id, teacher_id, part_id) VALUES (4, 1025, 4);

COMMIT;

BEGIN;

INSERT INTO eichah (perek_id, teacher_id, part_id) VALUES (0, 1026, 4);
INSERT INTO eichah (perek_id, teacher_id, part_id) VALUES (1, 1026, 4);
INSERT INTO eichah (perek_id, teacher_id, part_id) VALUES (2, 1026, 4);
INSERT INTO eichah (perek_id, teacher_id, part_id) VALUES (3, 1026, 4);
INSERT INTO eichah (perek_id, teacher_id, part_id) VALUES (4, 1026, 4);
INSERT INTO eichah (perek_id, teacher_id, part_id) VALUES (5, 1026, 4);

COMMIT;

BEGIN;

INSERT INTO kohelet (perek_id, teacher_id, part_id) VALUES (0, 1026, 4);
INSERT INTO kohelet (perek_id, teacher_id, part_id) VALUES (1, 1026, 4);
INSERT INTO kohelet (perek_id, teacher_id, part_id, is_many_parts, parts_breakdown) VALUES (2, 1026, 4, true, 'a,b');
INSERT INTO kohelet (perek_id, teacher_id, part_id) VALUES (3, 1026, 4);
INSERT INTO kohelet (perek_id, teacher_id, part_id) VALUES (4, 1026, 4);
INSERT INTO kohelet (perek_id, teacher_id, part_id) VALUES (5, 1026, 4);
INSERT INTO kohelet (perek_id, teacher_id, part_id) VALUES (6, 1026, 4);
INSERT INTO kohelet (perek_id, teacher_id, part_id) VALUES (7, 1026, 4);
INSERT INTO kohelet (perek_id, teacher_id, part_id) VALUES (8, 1026, 4);
INSERT INTO kohelet (perek_id, teacher_id, part_id) VALUES (9, 1026, 4);
INSERT INTO kohelet (perek_id, teacher_id, part_id) VALUES (10, 1026, 4);
INSERT INTO kohelet (perek_id, teacher_id, part_id) VALUES (11, 1026, 4);
INSERT INTO kohelet (perek_id, teacher_id, part_id) VALUES (12, 1026, 4);

COMMIT;

BEGIN;

INSERT INTO esther (perek_id, teacher_id, part_id) VALUES (1, 1027, 4);
INSERT INTO esther (perek_id, teacher_id, part_id) VALUES (2, 1027, 4);
INSERT INTO esther (perek_id, teacher_id, part_id) VALUES (3, 1027, 4);
INSERT INTO esther (perek_id, teacher_id, part_id) VALUES (4, 1027, 4);
INSERT INTO esther (perek_id, teacher_id, part_id) VALUES (5, 1027, 4);
INSERT INTO esther (perek_id, teacher_id, part_id) VALUES (6, 1027, 4);
INSERT INTO esther (perek_id, teacher_id, part_id) VALUES (7, 1027, 4);
INSERT INTO esther (perek_id, teacher_id, part_id) VALUES (8, 1027, 4);
INSERT INTO esther (perek_id, teacher_id, part_id) VALUES (9, 1027, 4);
INSERT INTO esther (perek_id, teacher_id, part_id) VALUES (10, 1027, 4);

COMMIT;
